---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - "2181"
      - "2888"
      - "32181"
      - "3888"
    extra_hosts:
      - "moby:127.0.0.1"


  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    expose:
      - "9092"
      - "29092"
    extra_hosts:
      - "moby:127.0.0.1"

  cloudera:
    image: midsw205/hadoop:0.0.2
    #image: cloudera/quickstart:latest
    hostname: cloudera
    privileged: true #NEW
    expose:
      - "8020" # nn
      - "8888" # hue
      - "9083" # hive thrift
      - "10000" # hive jdbc
      - "50070" # nn http
    volumes: #optional
      - ~/w205/project-3-spanesarmids/Hive:/w205
    ports:
      - "8888:8888"
    extra_hosts:
      - "moby:127.0.0.1"
    #command: /usr/bin/docker-quickstart #NEW

  spark:
    image: midsw205/spark-python:0.0.6
    stdin_open: true
    expose:
        - "8888"
#    ports:
        #- "8889:8888"
        #- "8888:8888"
    stdin_open: true
    tty: true
    volumes:
      - ~/w205:/w205
    depends_on:
      - cloudera
    environment:
      HADOOP_NAMENODE: cloudera
      HIVE_THRIFTSERVER: cloudera:9083
    extra_hosts:
      - "moby:127.0.0.1"
    command: env PYSPARK_DRIVER_PYTHON=jupyter PYSPARK_DRIVER_PYTHON_OPTS="notebook --no-browser --port 8888 --ip 0.0.0.0 --allow-root --notebook-dir=/w205/ " pyspark

  api_bridge:
    image: midsw205/base:latest
    stdin_open: true
    tty: true
    volumes:
      - ~/w205/project-3-spanesarmids/API_Bridge:/w205

  flask:
    image: midsw205/base:latest
    stdin_open: true
    tty: true
    volumes:
      - ~/w205/project-3-spanesarmids/Flask:/w205
    expose:
      - "5000" # Flask Port
    #command: "pip install flask_restful sqlalchemy flask_httpauth"

  presto:
    image: midsw205/presto:0.0.1
    hostname: presto
    volumes:
      - ~/w205:/w205
    expose:
      - "8080"
    environment:
      HIVE_THRIFTSERVER: cloudera:9083
    extra_hosts:
      - "moby:127.0.0.1"